# inventory/hosts.yml
all:
  hosts:
    avail_zksync:  # This is the name of your host
      ansible_host: your-ip-here  # Replace with actual IP
      ansible_user: ubuntu        # Replace with your SSH user
      ansible_port: 22           # SSH port, default is 22
      # ansible_ssh_private_key_file: ~/.ssh/your-key.pem  # Uncomment and specify your SSH key if needed
      
  vars:
    # Common variables for all hosts
    ansible_python_interpreter: /usr/bin/python3
    # Add any global variables here

  children:
    # You can group hosts here as you add more
    zksync_nodes:
      hosts:
        avail_zksync: